version: "3.9"
services:
  # backstage-backend:
  #   image: backstage-backend
  #   build: ./packages/backend
  #   container_name: backstage-backend
  #   ports:
  #     - "7007:7007"
  #   depends_on:
  #     - postgresql
  #   networks:
  #     backstage:
  #   restart: always

  postgresql:
    image: postgres:15.3
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=123456789"
    networks:
      backstage:
    restart: always

networks:
  backstage:
    ipam:
      driver: default
      config:
        - subnet: "192.168.90.0/24"
